### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by icetea-dev** [KitsuneLab-Development/K4-Zenith#21]
Hello, i just installed the plugin and when i enter on the server i get this error and that make the server low as fuck

2024-09-21 14:54:29.008 +00:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Cannot set or get 'CCSPlayerController::m_iCompetitiveWins' with "FollowCS2ServerGuidelines" option enabled.
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaOffset(String className, String propertyName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 62
   at CounterStrikeSharp.API.Core.CCSPlayerController.get_CompetitiveWins() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CCSPlayerController.g.cs:line 135
   at Zenith_Ranks.Plugin.SetCompetitiveRank(IPlayerServices player, Int32 mode, Int32 rankId, Int64 currentPoints, Int32 rankMax, Int32 rankBase, Int32 rankMargin)
   at Zenith_Ranks.Plugin.UpdateScoreboards()
   at InvokeStub_OnTick.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass51_0`1.<RegisterListener>b__2(ScriptContext context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 298
   at InvokeStub_Action`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context)

**Comment by Armageddon87270** [comment]
hi,
---> System.Exception: Cannot set or get 'CCSPlayerController::m_iCompetitiveWins' with "FollowCS2ServerGuidelines" option enabled.
[18:56]
Disable follow cs2 server guidelines in core.cfg in configs
[18:56]
This is due to fake ranks
